// Generated by export-sheet-to-json.js
// Last updated: 2025-04-12T21:31:53.334Z

export const TOOL_DATA = [
  {
    "id": "1",
    "name": "ChatGPT",
    "source_url": "https://chatgpt.com/",
    "short_description": "OpenAI\u2019s AI assistant for writing, research, and automation.",
    "screenshot_url": "/screenshots/chatgpt.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "2",
    "name": "Claude",
    "source_url": "https://claude.ai/",
    "short_description": "Conversational AI focused on safety, clarity, and helpfulness.",
    "screenshot_url": "/screenshots/claude.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "3",
    "name": "Perplexity",
    "source_url": "https://www.perplexity.ai/",
    "short_description": "AI search engine with real-time answers and citations.",
    "screenshot_url": "/screenshots/perplexity.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "4",
    "name": "Copilot",
    "source_url": "https://copilot.microsoft.com/",
    "short_description": "Microsoft\u2019s AI assistant built into Word, Excel, and more.",
    "screenshot_url": "/screenshots/copilot.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "5",
    "name": "Gemini",
    "source_url": "https://gemini.google.com/",
    "short_description": "Google\u2019s multimodal AI for search, productivity, and content.",
    "screenshot_url": "/screenshots/gemini.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "6",
    "name": "DeepSeek",
    "source_url": "https://www.deepseek.com/",
    "short_description": "Real-time AI chatbot with web and image generation capabilities.",
    "screenshot_url": "/screenshots/deepseek.png",
    "category": "Foundational AI",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "7",
    "name": "Jasper",
    "source_url": "https://www.jasper.ai",
    "short_description": "AI copywriter for blogs, marketing, and social media content.",
    "screenshot_url": "/screenshots/jasper.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "8",
    "name": "Copy.ai",
    "source_url": "https://www.copy.ai",
    "short_description": "Templates for sales copy, email, product descriptions, and more.",
    "screenshot_url": "/screenshots/copy.ai.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "9",
    "name": "Rytr",
    "source_url": "https://rytr.me",
    "short_description": "Budget-friendly AI writing assistant for fast drafting and editing.",
    "screenshot_url": "/screenshots/rytr.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "10",
    "name": "GrammarlyGO",
    "source_url": "https://www.grammarly.com",
    "short_description": "AI-powered writing assistant that rewrites, summarizes, and ideates.",
    "screenshot_url": "/screenshots/grammarlygo.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "11",
    "name": "Wordtune",
    "source_url": "https://www.wordtune.com",
    "short_description": "Rephrasing tool that improves tone, clarity, and impact.",
    "screenshot_url": "/screenshots/wordtune.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "12",
    "name": "Sudowrite",
    "source_url": "https://www.sudowrite.com",
    "short_description": "Creative AI writer to help with storytelling and idea generation.",
    "screenshot_url": "/screenshots/sudowrite.png",
    "category": "Writing & Editing",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "13",
    "name": "Otter.ai",
    "source_url": "https://otter.ai",
    "short_description": "Transcribes and summarizes meetings in real-time.",
    "screenshot_url": "/screenshots/otter.ai.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "14",
    "name": "Fireflies.ai",
    "source_url": "https://fireflies.ai",
    "short_description": "AI meeting recorder with notes, summaries, and topic detection.",
    "screenshot_url": "/screenshots/fireflies.ai.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "15",
    "name": "Fathom",
    "source_url": "https://fathom.video",
    "short_description": "Zoom and Meet notetaker with highlight tagging and sharing.",
    "screenshot_url": "/screenshots/fathom.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "16",
    "name": "tl;dv",
    "source_url": "https://tldv.io",
    "short_description": "Tag and search meeting recordings, integrated with major platforms.",
    "screenshot_url": "/screenshots/tl;dv.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "17",
    "name": "Avoma",
    "source_url": "https://www.avoma.com",
    "short_description": "Full meeting assistant with transcription, insights, and action items.",
    "screenshot_url": "/screenshots/avoma.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "18",
    "name": "Sembly",
    "source_url": "https://www.sembly.ai",
    "short_description": "AI meeting assistant with advanced transcription, summaries, and insights.",
    "screenshot_url": "/screenshots/sembly.png",
    "category": "Meeting Assistants",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "19",
    "name": "Lightfield (formerly Tome)",
    "source_url": "https://lightfield.app",
    "short_description": "Generate professional decks and narratives from prompts.",
    "screenshot_url": "/screenshots/tome.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "20",
    "name": "Gamma",
    "source_url": "https://gamma.app",
    "short_description": "Create AI-powered presentations or one-pagers in minutes.",
    "screenshot_url": "/screenshots/gamma.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "21",
    "name": "Beautiful.ai",
    "source_url": "https://www.beautiful.ai",
    "short_description": "Design presentations quickly with smart templates.",
    "screenshot_url": "/screenshots/beautiful.ai.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "22",
    "name": "Pitch",
    "source_url": "https://pitch.com",
    "short_description": "Collaborative presentation software with AI-powered design features.",
    "screenshot_url": "/screenshots/pitch.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "23",
    "name": "Plus AI",
    "source_url": "https://www.plus.ai",
    "short_description": "Slide generator for Google Slides & PowerPoint.",
    "screenshot_url": "/screenshots/plus_ai.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "24",
    "name": "Canva",
    "source_url": "https://www.canva.com",
    "short_description": "Auto-design slide decks using brand elements and copy.",
    "screenshot_url": "/screenshots/canva.png",
    "category": "Deck Automation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "25",
    "name": "Midjourney",
    "source_url": "https://www.midjourney.com",
    "short_description": "Generate stunning images for branding, merch, or social.",
    "screenshot_url": "/screenshots/midjourney.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "26",
    "name": "Bing ",
    "source_url": "https://www.bing.com/images/create",
    "short_description": "DALL\u00b7E 3-powered tool for custom AI illustrations.",
    "screenshot_url": "/screenshots/bing_.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "27",
    "name": "Synthesia",
    "source_url": "https://www.synthesia.io",
    "short_description": "Turn text into AI videos with avatars for internal comms or fan videos.",
    "screenshot_url": "/screenshots/synthesia.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "28",
    "name": "Runway",
    "source_url": "https://runwayml.com",
    "short_description": "Edit or generate videos using Gen-2 and AI effects.",
    "screenshot_url": "/screenshots/runway.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "29",
    "name": "Leonardo AI",
    "source_url": "https://leonardo.ai",
    "short_description": "AI-powered creative platform for generating stunning visual content and artwork.",
    "screenshot_url": "/screenshots/leonardo_ai.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "30",
    "name": "Adobe Firefly",
    "source_url": "https://firefly.adobe.com",
    "short_description": "Generate branded visuals and effects using prompts.",
    "screenshot_url": "/screenshots/adobe_firefly.png",
    "category": "Content Creation",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "31",
    "name": "Motion",
    "source_url": "https://www.usemotion.com",
    "short_description": "AI calendar that schedules tasks and meetings automatically.",
    "screenshot_url": "/screenshots/motion.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "32",
    "name": "Reclaim.ai",
    "source_url": "https://reclaim.ai",
    "short_description": "Auto-schedules tasks and routines into your calendar.",
    "screenshot_url": "/screenshots/reclaim.ai.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "33",
    "name": "Clockwise",
    "source_url": "https://www.getclockwise.com",
    "short_description": "Calendar optimizer that creates more focus time.",
    "screenshot_url": "/screenshots/clockwise.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "34",
    "name": "Magical",
    "source_url": "https://www.getmagical.com",
    "short_description": "Automate form-filling, email replies, and workflows with text prompts.",
    "screenshot_url": "/screenshots/magical.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "35",
    "name": "Notion AI",
    "source_url": "https://www.notion.so",
    "short_description": "Smart AI assistant inside Notion to summarize and answer.",
    "screenshot_url": "/screenshots/notion_ai.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "36",
    "name": "Sunsama",
    "source_url": "https://sunsama.com",
    "short_description": "Daily planner that helps prioritize, plan, and reflect on goals.",
    "screenshot_url": "/screenshots/sunsama.png",
    "category": "Task & Workflow",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "37",
    "name": "Elicit",
    "source_url": "https://elicit.com/",
    "short_description": "Research assistant that reviews academic papers and finds insights.",
    "screenshot_url": "/screenshots/elicit.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "38",
    "name": "Perplexity",
    "source_url": "https://www.perplexity.ai",
    "short_description": "Search engine with citations and real-time knowledge.",
    "screenshot_url": "/screenshots/perplexity.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "39",
    "name": "Humata",
    "source_url": "https://humata.ai",
    "short_description": "Ask questions and summarize long PDFs instantly.",
    "screenshot_url": "/screenshots/humata.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "40",
    "name": "SciSpace",
    "source_url": "https://www.scispace.com",
    "short_description": "Understand and query scientific papers in plain English.",
    "screenshot_url": "/screenshots/scispace.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "41",
    "name": "Consensus",
    "source_url": "https://consensus.app",
    "short_description": "AI-powered academic search engine that finds insights from research papers.",
    "screenshot_url": "/screenshots/consensus.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "42",
    "name": "Wolfram",
    "source_url": "https://www.wolframalpha.com",
    "short_description": "Computational engine for data, stats, and analytics.",
    "screenshot_url": "/screenshots/wolfram.png",
    "category": "Research & Analysis",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "43",
    "name": "SnackPrompt",
    "source_url": "https://www.snackprompt.com",
    "short_description": "Discover, test, and learn prompt engineering through curated examples and community-shared ideas.",
    "screenshot_url": "/screenshots/snackprompt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "44",
    "name": "LearnPrompting",
    "source_url": "https://learnprompting.org",
    "short_description": "Free open-source course that teaches prompt engineering and AI fundamentals from beginner to advanced.",
    "screenshot_url": "/screenshots/learnprompting.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "45",
    "name": "AI Camp",
    "source_url": "https://www.ai-camp.org",
    "short_description": "Hands-on learning program that helps non-technical users understand and build real-world AI projects.",
    "screenshot_url": "/screenshots/ai_camp.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "46",
    "name": "FlowGPT",
    "source_url": "https://flowgpt.com",
    "short_description": "Explore, save, and learn from AI-generated prompts across different industries and workflows.",
    "screenshot_url": "/screenshots/flowgpt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "47",
    "name": "PromptHero",
    "source_url": "https://www.prompthero.com",
    "short_description": "Search engine and marketplace for prompt templates \u2014 great for learning prompt structures by example.",
    "screenshot_url": "/screenshots/prompthero.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "48",
    "name": "SuperPrompt",
    "source_url": "https://superprompt.com",
    "short_description": "Interactive prompt-building assistant that helps users understand how AI models respond to inputs.",
    "screenshot_url": "/screenshots/superprompt.png",
    "category": "Learning & Skills",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "49",
    "name": "ElevenLabs",
    "source_url": "https://elevenlabs.io",
    "short_description": "High-fidelity text-to-speech with voice cloning.",
    "screenshot_url": "/screenshots/elevenlabs.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "50",
    "name": "Murf.ai",
    "source_url": "https://murf.ai",
    "short_description": "Create studio-quality voiceovers in multiple accents/languages.",
    "screenshot_url": "/screenshots/murf.ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "51",
    "name": "Resemble AI",
    "source_url": "https://www.resemble.ai",
    "short_description": "Clone voices and generate custom speech with APIs.",
    "screenshot_url": "/screenshots/resemble_ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "52",
    "name": "Speechify",
    "source_url": "https://speechify.com",
    "short_description": "Turn any text into spoken word with natural narration.",
    "screenshot_url": "/screenshots/speechify.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "53",
    "name": "Bland.ai",
    "source_url": "https://www.bland.ai",
    "short_description": "AI voice agents that make and receive phone calls with natural conversations.",
    "screenshot_url": "/screenshots/bland.ai.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "54",
    "name": "Play.ht",
    "source_url": "https://play.ht",
    "short_description": "Generate podcast-quality speech from text or scripts.",
    "screenshot_url": "/screenshots/play.ht.png",
    "category": "Voice & Audio",
    "type": "personal",
    "sector": "N/A"
  },
  {
    "id": "55",
    "name": "AutoGPT",
    "source_url": "https://github.com/Significant-Gravitas/AutoGPT",
    "short_description": "Autonomous AI agent that performs multi-step tasks",
    "screenshot_url": "/screenshots/autogpt.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "56",
    "name": "CrewAI",
    "source_url": "https://www.crewai.com/",
    "short_description": "Framework for agent collaboration in task execution",
    "screenshot_url": "/screenshots/crewai.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "57",
    "name": "Cognosys",
    "source_url": "https://www.cognosys.ai/",
    "short_description": "Browser-native autonomous AI agent",
    "screenshot_url": "/screenshots/cognosys.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "58",
    "name": "Superagent",
    "source_url": "https://superagent.sh/",
    "short_description": "Open-source framework for AI agents with memory",
    "screenshot_url": "/screenshots/superagent.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "59",
    "name": "Replit",
    "source_url": "https://replit.com/",
    "short_description": "Collaborative browser-based IDE with AI coding assistant.",
    "screenshot_url": "/screenshots/replit.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "60",
    "name": "BabyAGI",
    "source_url": "https://github.com/yoheinakajima/babyagi",
    "short_description": "Task-driven autonomous agent framework for complex problem solving.",
    "screenshot_url": "/screenshots/babyagi.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Agent Builders"
  },
  {
    "id": "61",
    "name": "LangChain",
    "source_url": "https://www.langchain.com/",
    "short_description": "Framework to build LLM-powered applications",
    "screenshot_url": "/screenshots/langchain.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "62",
    "name": "Dust.tt",
    "source_url": "https://dust.tt/",
    "short_description": "LLM orchestration for enterprise teams",
    "screenshot_url": "/screenshots/dust.tt.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "63",
    "name": "Flowise",
    "source_url": "https://flowiseai.com/",
    "short_description": "Drag & drop LLM orchestration UI",
    "screenshot_url": "/screenshots/flowise.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "64",
    "name": "PromptLayer",
    "source_url": "https://promptlayer.com/",
    "short_description": "Prompt management and observability for LLMs",
    "screenshot_url": "/screenshots/promptlayer.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "65",
    "name": "LlamaIndex",
    "source_url": "https://www.llamaindex.ai/",
    "short_description": "Framework to connect data to LLMs",
    "screenshot_url": "/screenshots/llamaindex.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "66",
    "name": "Haystack",
    "source_url": "https://haystack.deepset.ai",
    "short_description": "Open-source LLM orchestration framework for building AI applications.",
    "screenshot_url": "/screenshots/haystack.png",
    "category": "None",
    "type": "enterprise",
    "sector": "LLM Frameworks & Orchestration"
  },
  {
    "id": "67",
    "name": "Hugging Face",
    "source_url": "https://huggingface.co/",
    "short_description": "Model hub and ML library for transformers",
    "screenshot_url": "/screenshots/hugging_face.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "68",
    "name": "Replicate",
    "source_url": "https://replicate.com/",
    "short_description": "Run and deploy ML models via API",
    "screenshot_url": "/screenshots/replicate.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "69",
    "name": "OpenPipe",
    "source_url": "https://www.openpipe.ai/",
    "short_description": "Fine-tuning platform for LLMs with trace feedback",
    "screenshot_url": "/screenshots/openpipe.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "70",
    "name": "Modal",
    "source_url": "https://modal.com/",
    "short_description": "Serverless platform for running Python apps with AI",
    "screenshot_url": "/screenshots/modal.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "71",
    "name": "Cohere",
    "source_url": "https://cohere.com",
    "short_description": "Enterprise LLM platform with powerful language models and APIs.",
    "screenshot_url": "/screenshots/cohere.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "72",
    "name": "Together.ai",
    "source_url": "https://www.together.ai/",
    "short_description": "Model serving and inference API for LLMs",
    "screenshot_url": "/screenshots/together.ai.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Model Hubs & Customization"
  },
  {
    "id": "73",
    "name": "Replit Ghostwriter",
    "source_url": "https://replit.com/",
    "short_description": "AI coding assistant integrated into Replit IDE",
    "screenshot_url": "/screenshots/replit_ghostwriter.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "74",
    "name": "CodeGeeX",
    "source_url": "https://codegeex.cn/en-US",
    "short_description": "Multilingual AI coding assistant supporting 20+ programming languages.",
    "screenshot_url": "/screenshots/codegeex.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "75",
    "name": "Cursor",
    "source_url": "https://cursor.com/en",
    "short_description": "AI-first code editor built on VS Code",
    "screenshot_url": "/screenshots/cursor.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "76",
    "name": "Windsurf (formerly Codeium)",
    "source_url": "https://windsurf.com",
    "short_description": "Free AI-powered coding assistant with deep IDE integration and fast autocomplete for over 70 languages.",
    "screenshot_url": "/screenshots/codeium.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "77",
    "name": "Continue",
    "source_url": "https://continue.dev/",
    "short_description": "Open-source autopilot for coding",
    "screenshot_url": "/screenshots/continue.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "78",
    "name": "Amazon CodeWhisperer",
    "source_url": "https://aws.amazon.com/codewhisperer/",
    "short_description": "AI coding companion from AWS with security scanning and code suggestions.",
    "screenshot_url": "/screenshots/amazon_codewhisperer.png",
    "category": "None",
    "type": "enterprise",
    "sector": "AI Coding & App Platforms"
  },
  {
    "id": "79",
    "name": "Pinecone",
    "source_url": "https://www.pinecone.io/",
    "short_description": "Vector database for semantic search and memory",
    "screenshot_url": "/screenshots/pinecone.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "80",
    "name": "Weaviate",
    "source_url": "https://weaviate.io/",
    "short_description": "Open-source vector search engine",
    "screenshot_url": "/screenshots/weaviate.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "81",
    "name": "Chroma",
    "source_url": "https://www.trychroma.com/",
    "short_description": "Embedding store for building AI apps",
    "screenshot_url": "/screenshots/chroma.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "82",
    "name": "Zep",
    "source_url": "https://getzep.com/",
    "short_description": "Memory server for LLM applications",
    "screenshot_url": "/screenshots/zep.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "83",
    "name": "Milvus",
    "source_url": "https://milvus.io/",
    "short_description": "Scalable vector database for similarity search",
    "screenshot_url": "/screenshots/milvus.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "84",
    "name": "Qdrant",
    "source_url": "https://qdrant.tech/",
    "short_description": "Open-source vector similarity search engine",
    "screenshot_url": "/screenshots/qdrant.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Embeddings & Vector Search"
  },
  {
    "id": "85",
    "name": "Glean",
    "source_url": "https://www.glean.com/",
    "short_description": "AI-powered workplace search that indexes and understands company knowledge",
    "screenshot_url": "/screenshots/glean.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  },
  {
    "id": "86",
    "name": "Hebbia",
    "source_url": "https://www.hebbia.com",
    "short_description": "Semantic search engine designed for complex enterprise queries across documents",
    "screenshot_url": "/screenshots/hebbia.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  },
  {
    "id": "87",
    "name": "Seite",
    "source_url": "https://seite.ai",
    "short_description": "AI search tool designed for academic research and technical documentation.",
    "screenshot_url": "/screenshots/seite.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  },
  {
    "id": "88",
    "name": "Vectara",
    "source_url": "https://www.vectara.com/",
    "short_description": "RAG-native platform offering semantic search with safety and relevance tuning",
    "screenshot_url": "/screenshots/vectara.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  },
  {
    "id": "89",
    "name": "Slack AI",
    "source_url": "https://slack.com/features/ai",
    "short_description": "Built-in AI features for Slack including search, summaries, and insights.",
    "screenshot_url": "/screenshots/slack_ai.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  },
  {
    "id": "90",
    "name": "You.com API",
    "source_url": "https://you.com/api",
    "short_description": "Enables personalized, private LLM-powered search for apps and platforms",
    "screenshot_url": "/screenshots/you.com_api.png",
    "category": "None",
    "type": "enterprise",
    "sector": "Enterprise Search & QA"
  }
];